# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-6.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-6.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-6.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tpeterka/tess-cgal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tpeterka/tess-cgal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-6.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-6.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tpeterka/tess-cgal/CMakeFiles /Users/tpeterka/tess-cgal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tpeterka/tess-cgal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dense

# Build rule for target.
dense: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dense
.PHONY : dense

# fast build rule for target.
dense/fast:
	$(MAKE) -f lib/CMakeFiles/dense.dir/build.make lib/CMakeFiles/dense.dir/build
.PHONY : dense/fast

#=============================================================================
# Target rules for targets named draw

# Build rule for target.
draw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draw
.PHONY : draw

# fast build rule for target.
draw/fast:
	$(MAKE) -f lib/CMakeFiles/draw.dir/build.make lib/CMakeFiles/draw.dir/build
.PHONY : draw/fast

#=============================================================================
# Target rules for targets named dump

# Build rule for target.
dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dump
.PHONY : dump

# fast build rule for target.
dump/fast:
	$(MAKE) -f lib/CMakeFiles/dump.dir/build.make lib/CMakeFiles/dump.dir/build
.PHONY : dump/fast

#=============================================================================
# Target rules for targets named tess

# Build rule for target.
tess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tess
.PHONY : tess

# fast build rule for target.
tess/fast:
	$(MAKE) -f lib/CMakeFiles/tess.dir/build.make lib/CMakeFiles/tess.dir/build
.PHONY : tess/fast

#=============================================================================
# Target rules for targets named voronoi

# Build rule for target.
voronoi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voronoi
.PHONY : voronoi

# fast build rule for target.
voronoi/fast:
	$(MAKE) -f driver/CMakeFiles/voronoi.dir/build.make driver/CMakeFiles/voronoi.dir/build
.PHONY : voronoi/fast

#=============================================================================
# Target rules for targets named post-voronoi

# Build rule for target.
post-voronoi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 post-voronoi
.PHONY : post-voronoi

# fast build rule for target.
post-voronoi/fast:
	$(MAKE) -f postprocessor/CMakeFiles/post-voronoi.dir/build.make postprocessor/CMakeFiles/post-voronoi.dir/build
.PHONY : post-voronoi/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dense"
	@echo "... draw"
	@echo "... dump"
	@echo "... tess"
	@echo "... voronoi"
	@echo "... post-voronoi"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

